package DCRS;


/**
* DCRS/computeTaskInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/eclipse_workspace/Project/src/DCRS.idl
* Monday, November 26, 2018 9:10:14 o'clock PM EST
*/

public interface computeTaskInterface extends computeTaskInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface computeTaskInterface
