package DCRS;


/**
* DCRS/computeTaskInterfacePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/eclipse_workspace/Project/src/DCRS.idl
* Monday, November 26, 2018 9:10:14 o'clock PM EST
*/

public abstract class computeTaskInterfacePOA extends org.omg.PortableServer.Servant
 implements DCRS.computeTaskInterfaceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("checkRegistration", new java.lang.Integer (0));
    _methods.put ("enrollCourse", new java.lang.Integer (1));
    _methods.put ("getClassSchedule", new java.lang.Integer (2));
    _methods.put ("dropCourse", new java.lang.Integer (3));
    _methods.put ("swapCourse", new java.lang.Integer (4));
    _methods.put ("addCourse", new java.lang.Integer (5));
    _methods.put ("removeCourse", new java.lang.Integer (6));
    _methods.put ("listCourseAvailability", new java.lang.Integer (7));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // DCRS/computeTaskInterface/checkRegistration
       {
         String msg = in.read_string ();
         int $result = (int)0;
         $result = this.checkRegistration (msg);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // DCRS/computeTaskInterface/enrollCourse
       {
         String msg = in.read_string ();
         String $result = null;
         $result = this.enrollCourse (msg);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // DCRS/computeTaskInterface/getClassSchedule
       {
         String msg = in.read_string ();
         String $result = null;
         $result = this.getClassSchedule (msg);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // DCRS/computeTaskInterface/dropCourse
       {
         String msg = in.read_string ();
         String $result = null;
         $result = this.dropCourse (msg);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // DCRS/computeTaskInterface/swapCourse
       {
         String msg = in.read_string ();
         String $result = null;
         $result = this.swapCourse (msg);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // DCRS/computeTaskInterface/addCourse
       {
         String msg = in.read_string ();
         String $result = null;
         $result = this.addCourse (msg);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 6:  // DCRS/computeTaskInterface/removeCourse
       {
         String msg = in.read_string ();
         String $result = null;
         $result = this.removeCourse (msg);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 7:  // DCRS/computeTaskInterface/listCourseAvailability
       {
         String msg = in.read_string ();
         String $result = null;
         $result = this.listCourseAvailability (msg);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:DCRS/computeTaskInterface:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public computeTaskInterface _this() 
  {
    return computeTaskInterfaceHelper.narrow(
    super._this_object());
  }

  public computeTaskInterface _this(org.omg.CORBA.ORB orb) 
  {
    return computeTaskInterfaceHelper.narrow(
    super._this_object(orb));
  }


} // class computeTaskInterfacePOA
