package DCRS;


/**
* DCRS/computeTaskInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/eclipse_workspace/Project/src/DCRS.idl
* Monday, November 26, 2018 9:10:14 o'clock PM EST
*/

public interface computeTaskInterfaceOperations 
{
  int checkRegistration (String msg);
  String enrollCourse (String msg);
  String getClassSchedule (String msg);
  String dropCourse (String msg);
  String swapCourse (String msg);
  String addCourse (String msg);
  String removeCourse (String msg);
  String listCourseAvailability (String msg);
} // interface computeTaskInterfaceOperations
