package DcrsApp;


/**
* DcrsApp/Dcrs.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/Suhel/workspace/DcrsUsingCorba/src/dcrs.idl
* Wednesday, 24 October, 2018 4:11:04 PM EDT
*/

public interface Dcrs extends DcrsOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Dcrs
