package DcrsApp;


/**
* DcrsApp/DcrsOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/Suhel/workspace/DcrsUsingCorba/src/dcrs.idl
* Wednesday, 24 October, 2018 4:11:04 PM EDT
*/

public interface DcrsOperations 
{
  void shutdown ();

  // Advisor Functions
  String addCourse (String courseID, String semester);
  String removeCourse (String courseID, String semester);
  String listCourseAvailability (String semester);

  //Student Functions
  String enrolCourse (String studentID, String courseID, String semester);
  String getClassSchedule (String studentID);
  String dropCourse (String studentID, String courseID);
  String swapCourse (String studentId, String newCourseId, String oldCourseId);

  //helper methods
  int checkRegistration (String studentId);
  String registerNewUser (String studentId);
  void setUser (String user);
  String getUser ();
  void setCapacity (int capacity);
  int getCapacity ();
} // interface DcrsOperations
