package DcrsApp;


/**
* DcrsApp/DcrsHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/Suhel/workspace/DcrsUsingCorba/src/dcrs.idl
* Wednesday, 24 October, 2018 4:11:04 PM EDT
*/

abstract public class DcrsHelper
{
  private static String  _id = "IDL:DcrsApp/Dcrs:1.0";

  public static void insert (org.omg.CORBA.Any a, DcrsApp.Dcrs that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static DcrsApp.Dcrs extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (DcrsApp.DcrsHelper.id (), "Dcrs");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static DcrsApp.Dcrs read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_DcrsStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, DcrsApp.Dcrs value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static DcrsApp.Dcrs narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof DcrsApp.Dcrs)
      return (DcrsApp.Dcrs)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      DcrsApp._DcrsStub stub = new DcrsApp._DcrsStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static DcrsApp.Dcrs unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof DcrsApp.Dcrs)
      return (DcrsApp.Dcrs)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      DcrsApp._DcrsStub stub = new DcrsApp._DcrsStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
