package DcrsApp;


/**
* DcrsApp/DcrsPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/Suhel/workspace/DcrsUsingCorba/src/dcrs.idl
* Wednesday, 24 October, 2018 4:11:04 PM EDT
*/

public abstract class DcrsPOA extends org.omg.PortableServer.Servant
 implements DcrsApp.DcrsOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("shutdown", new java.lang.Integer (0));
    _methods.put ("addCourse", new java.lang.Integer (1));
    _methods.put ("removeCourse", new java.lang.Integer (2));
    _methods.put ("listCourseAvailability", new java.lang.Integer (3));
    _methods.put ("enrolCourse", new java.lang.Integer (4));
    _methods.put ("getClassSchedule", new java.lang.Integer (5));
    _methods.put ("dropCourse", new java.lang.Integer (6));
    _methods.put ("swapCourse", new java.lang.Integer (7));
    _methods.put ("checkRegistration", new java.lang.Integer (8));
    _methods.put ("registerNewUser", new java.lang.Integer (9));
    _methods.put ("setUser", new java.lang.Integer (10));
    _methods.put ("getUser", new java.lang.Integer (11));
    _methods.put ("setCapacity", new java.lang.Integer (12));
    _methods.put ("getCapacity", new java.lang.Integer (13));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // DcrsApp/Dcrs/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }


  // Advisor Functions
       case 1:  // DcrsApp/Dcrs/addCourse
       {
         String courseID = in.read_string ();
         String semester = in.read_string ();
         String $result = null;
         $result = this.addCourse (courseID, semester);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // DcrsApp/Dcrs/removeCourse
       {
         String courseID = in.read_string ();
         String semester = in.read_string ();
         String $result = null;
         $result = this.removeCourse (courseID, semester);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // DcrsApp/Dcrs/listCourseAvailability
       {
         String semester = in.read_string ();
         String $result = null;
         $result = this.listCourseAvailability (semester);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }


  //Student Functions
       case 4:  // DcrsApp/Dcrs/enrolCourse
       {
         String studentID = in.read_string ();
         String courseID = in.read_string ();
         String semester = in.read_string ();
         String $result = null;
         $result = this.enrolCourse (studentID, courseID, semester);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // DcrsApp/Dcrs/getClassSchedule
       {
         String studentID = in.read_string ();
         String $result = null;
         $result = this.getClassSchedule (studentID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 6:  // DcrsApp/Dcrs/dropCourse
       {
         String studentID = in.read_string ();
         String courseID = in.read_string ();
         String $result = null;
         $result = this.dropCourse (studentID, courseID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 7:  // DcrsApp/Dcrs/swapCourse
       {
         String studentId = in.read_string ();
         String newCourseId = in.read_string ();
         String oldCourseId = in.read_string ();
         String $result = null;
         $result = this.swapCourse (studentId, newCourseId, oldCourseId);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }


  //helper methods
       case 8:  // DcrsApp/Dcrs/checkRegistration
       {
         String studentId = in.read_string ();
         int $result = (int)0;
         $result = this.checkRegistration (studentId);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 9:  // DcrsApp/Dcrs/registerNewUser
       {
         String studentId = in.read_string ();
         String $result = null;
         $result = this.registerNewUser (studentId);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 10:  // DcrsApp/Dcrs/setUser
       {
         String user = in.read_string ();
         this.setUser (user);
         out = $rh.createReply();
         break;
       }

       case 11:  // DcrsApp/Dcrs/getUser
       {
         String $result = null;
         $result = this.getUser ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 12:  // DcrsApp/Dcrs/setCapacity
       {
         int capacity = in.read_long ();
         this.setCapacity (capacity);
         out = $rh.createReply();
         break;
       }

       case 13:  // DcrsApp/Dcrs/getCapacity
       {
         int $result = (int)0;
         $result = this.getCapacity ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:DcrsApp/Dcrs:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Dcrs _this() 
  {
    return DcrsHelper.narrow(
    super._this_object());
  }

  public Dcrs _this(org.omg.CORBA.ORB orb) 
  {
    return DcrsHelper.narrow(
    super._this_object(orb));
  }


} // class DcrsPOA
